FROM python:3.8-slim
ARG GCP_DBT_KEY_PATH

RUN pip install streamlit

RUN mkdir /app
RUN mkdir /opt/streamlit

COPY ./streamlit_apps/requirements.txt ./
RUN pip install -r requirements.txt

# Copy service account key
COPY $GCP_DBT_KEY_PATH /opt/streamlit/gcp_key.json

WORKDIR /app


# Download spacy language data
RUN python -m spacy download en_core_web_md
RUN python -m spacy download en_core_web_sm

EXPOSE 8501

ENTRYPOINT ["streamlit", "run"]

CMD ["run_all.py", "apps/"]
