myreddit:
  outputs:
    dev:
      dataset: reddit
      fixed_retries: 1
      keyfile: "{{ env_var('GCP_DBT_KEY_PATH') }}"
      method: service-account
      location: europe-west1
      priority: interactive
      project: myreddit-338008
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev
