resources:
  reddit:
    config:
      secret: C3rwKVVuL-L8HkJ6fiDD8wvRsqDMyg
      app_id: 1PZH2AGk7VT9ISAAygpCAw
      username: Qualkeck
      password: GrMkAc7Hu&
      posts_limit: 100
      comments_limit: 100
      comments_depth: 10
  bigquery:
    config:
      project: myreddit-338008
  dbt:
    config:
      profiles_dir: /Users/yco/.dbt/
      project_dir: /Users/yco/dev/myreddit/dbt/
ops:
  reddit_el:
    ops:
      import_posts_to_bq:
        config:
          dataset: reddit_raw
          table: posts
      import_comments_to_bq:
        config:
          dataset: reddit_raw
          table: comments
  preprocess_texts:
    ops:
      load_clean_texts:
        config:
          dataset: reddit_texts
          table: posts_clean
